### ISSUE TITLE
Backup and restore functionality

### ISSUE THREAD

**Issue by simonhf** [andrewnimmo/rick-sanders-imap-tools#3]
I'm interested in using the backup and restore functionality.

1. Does anybody know if the backup and restore functionality is working correctly?

2. Once I backup to local disk, can I somehow search and prune certain emails myself in order to reduce the total emails when restoring? If so, how?

3. Is there some kind of user group or community for these tools? If so, where?

Thanks!

**Comment by andrewnimmo** [comment]
Hi

There is currently no support available for these tools. Feel free fork a copy for your own testing.
