### ISSUE TITLE
What is the status of the license for this source code?

### ISSUE THREAD

**Issue by simonhf** [andrewnimmo/rick-sanders-imap-tools#4]
As I understand things after Googling around: "When someone dies, unless their wills says otherwise, any copyrights go to their estate. It is up to their heirs what happens after that."

So what has happened regarding the copyright and license to this source code?

**Comment by gilleslamiral** [comment]
See the licence.txt file, it's ok to use and hack the scripts.

**Comment by andrewnimmo** [comment]
Following the death of Rick Sanders (December 21, 2016 ), the web page http://www.athensfbc.com/imap-tools/ was updated ([December 28, 2016](https://web.archive.org/web/20161228145952/http://www.athensfbc.com/imap_tools/)) and a copy of this is available at https://andrewnimmo.github.io/rick-sanders-imap-tools/.

I purchased a license in August 2015, and had a copy of version 1.347 which was released in March 2016. IMAP Tools version 1.347 was not the final release; I believe that subsequent changes were for minor bugs.
