### ISSUE TITLE
Does anybody tested this code? Typo

### ISSUE THREAD

**Issue by miamibc** [andrewnimmo/rick-sanders-imap-tools#5]
https://github.com/andrewnimmo/rick-sanders-imap-tools/blob/da4ba8fa3555bebfbdbf6e3d5ee4c47caac7fe48/delete_imap_mailboxes.pl#L398

**Comment by andrewnimmo** [comment]
Hi, this is a preserved copy of a set of tools that were [released](https://web.archive.org/web/20170302015826/http://www.athensfbc.com/imap-tools/) from the original license constraints. Please feel free to fork this repo to make any updates.
