### ISSUE TITLE
Rest In Peace, Richard Frank Sanders

### ISSUE THREAD

**Issue by jpwynn** [andrewnimmo/rick-sanders-imap-tools#6]
https://obittree.com/obituary/us/texas/athens/carroll-lehr-funeral-home/richard-sanders/2800914/index.php

**Comment by andrewnimmo** [comment]
https://stackexchange.com/users/3123399/rick-sanders
https://www.carroll-lehr.com/obituaries/Richard-Frank-Sanders?obId=2489864
https://www.tributearchive.com/obituaries/2489864/Richard-Frank-Sanders
